apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: flask
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: flask
spec:
  commonName: flask.sj3.in
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
